### ISSUE TITLE
RFC: @prismicio/next alpha feedback

### ISSUE THREAD

**Issue by dayhaysoos** [prismicio/prismic-next#4]
## Overview

`@prismic/next` is a new package designed for making Prismic easier to use with a NextJS project. The original RFC from @angeloashmore and provides more background:

https://github.com/prismicio/prismic-next/issues/1

At the moment, the package is mostly focused around making it easier to to set up Prismic Previews with Next. As Next and/or Prismic itself release more updates, it's possible that this package could grow and adapt to whatever new features come out if necessary.

For this RFC, we'd like to gather feedback on the implementation from a developer experience perspective. Should we be doing more, should we be doing less? Could things be done in an easier, simpler way for the end user?

### `enableClientServerSupport`

```js
export const enableClientServerSupport = (
	config: EnableClientServerSupportConfig,
): void => {
	if ("context" in config && config.context) {
		const previewData = config.context.previewData;

		if (isPrismicNextPreviewData(previewData) && previewData.ref) {
			config.client.queryContentFromRef(previewData.ref);
		}
	} else if ("req" in config && config.req) {
		config.client.enableAutoPreviewsFromReq(config.req);
	}
};
```
enableClientServerSupport is a function that allows the end user to enable Previews with either `PreviewData` coming from NextJS context or a Prismic ref coming from the NextApiRequest. It's intended to be used in an end users `createClient()` function, like this:

```js

import { enableClientServerSupport, CreateClientConfig } from 'prismic-next';

export const createClient = (config: CreateClientConfig) => {
  const client = Prismic.createClient(apiEndpoint);

  enableClientServerSupport({
    client,
    context: config.context,
    req: config.req,
  });

  return client;
};
```

One thing we've been wondering is whether or not `@prismic/next` should offer its own `createClient` function that would run `enableClientServerSupport` under the hood. On one hand, it'd be nice to not have to worry about creating your own client, however, the fear is that we might deal with feature creep as users might have more needs with creating client outside of what we provide.

Would love to get feedback on whether or not we might want to provide one on our own or leave it as is.

### `<PrismicPreview />`

The PrismicPreview component is to be wrapped around the entire NextJS app. There are two reasons why we have this component:

1. It's job is to add the PrismicToolbar to a NextJS app, there's a required param called `repoName` where you just pass it the name of your Prismic Repo and the correct URL for the toolbar is added in the necessary `<script />` tag.

2. There is a useEffect hook that adds event listeners that come from the Prismic Toolbar, so it can properly update when the Preview URL is triggered. It's listening for both `prismicPreviewUpdate` and `prismicPreviewEnd`.

By default, the updatePreviewURL is `/api/preview` and the exitPreviewURL is `/api/exit-preview`. The end user has an option to override both of those by passing their own URLs to the props. Here's what it looks like in usage:

```js
import { PrismicPreview } from 'prismic-next';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <PrismicPreview repoName='smashing-mag-nick-1'>
      <Component {...pageProps} />;
    </PrismicPreview>
  );
}

export default MyApp;
```

### `setPreviewData` & `redirectToPreviewURL`

These are actually really straight forward, to be used when the `prismicUpdatePreview` event gets triggered from the toolbar. Usage:

```js
import { linkResolver, createClient } from '../../prismic-config';
import * as prismicNext from 'prismic-next';
import { NextApiRequest, NextApiResponse } from 'next';

export default async (req: NextApiRequest, res: NextApiResponse) => {
  const client = createClient({ req });

  prismicNext.setPreviewData({ req, res });

  await prismicNext.redirectToPreviewURL({ res, client, linkResolver });
};
```

Here is how they look under the hood:

`redirectToPreviewURL`
```js
import { NextApiResponse } from "next";
import { Client } from "@prismicio/client";
import { LinkResolverFunction } from "@prismicio/helpers";

export type PreviewConfig = {
	res: NextApiResponse;
	client: Client;
	linkResolver: LinkResolverFunction;
};

export async function redirectToPreviewURL({
	res,
	client,
	linkResolver,
}: PreviewConfig): Promise<void> {
	const previewUrl = await client.resolvePreviewURL({
		linkResolver,
		defaultURL: "/",
	});

	res.redirect(previewUrl);
}
```
`setPreviewData`

```js
import { NextApiResponse, NextApiRequest } from "next";

export type PreviewConfig = {
	req: NextApiRequest;
	res: NextApiResponse;
};

export async function setPreviewData({
	req,
	res,
}: PreviewConfig): Promise<void> {
	const { token: ref } = req.query;

	res.setPreviewData({ ref });
}

```

### `exitPreview`

This one is also pretty straight forward. Usage:

```js
import { NextApiResponse } from 'next';
import { exitPreview } from 'prismic-next';

export default async function exit(_: any, res: NextApiResponse) {
  exitPreview(_, res);
}

```

Under the hood:

```js
export async function exitPreview(_: any, res: NextApiResponse): Promise<void> {
	// Exit the current user from "Preview Mode". This function accepts no args.
	res.clearPreviewData();

	// Redirect the user back to the index page.
	res.writeHead(307, { Location: "/" });
	res.end();
}
```

### Note

There is still some feedback left on these implementations that have yet to be applied, the intent of this RFC is to really focus on the end user usage, not collect feedback on the Pull Request itself. If you do want to give feedback about code quality, feel free to leave that feedback on the PR:

#3

**Comment by phillysnow** [comment]
Hey Guys,

Have you discussed dynamic route generation? It's something that's tricky at the minute for Next users. We try to offer some help with it by having users add a queries file that gets all documents in Prismic to build the dynamic paths.
https://prismic.io/docs/technologies/nextjs#3.3.-queries-file

It's also what `next-slicezone` was doing with `useGetStaticPaths` but we don't want to recommend this package anymore:
https://github.com/prismicio/slice-machine/tree/master/packages/next-slicezone#usegetstaticpaths

This would also allow first-class support for the Route Resolver which is very difficult to use with Next.js at the minute.

Thanks.

**Comment by Heyrows** [comment]
I don't know Next very well, does the preview works on a special page ?
I was wondering why ending the preview has to redirect you
```
export async function exitPreview(_: any, res: NextApiResponse): Promise<void> {
	// Exit the current user from "Preview Mode". This function accepts no args.
	res.clearPreviewData();

	// Redirect the user back to the index page.
	res.writeHead(307, { Location: "/" });
	res.end();
}
```
I would say ending the preview should just close the toolbar and maybe reload the current page if you need to.
I think it is only be displaying the same content without preview that the user can instantly see the difference and be sure that the preview is off.

**Comment by pvpg** [comment]
I have a question / comment. [Some users](https://community.prismic.io/t/security-header-x-content-type-options-and-prismic-previews/7998/3) have experienced issues with previews and Next when they add this [security header ](https://nextjs.org/docs/advanced-features/security-headers)in their project: [X-Content-Type-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options). The preview stops working.

I'd like to know if this version of the kit addresses this issue or if this is not related to Prismic at all?

**Comment by dayhaysoos** [comment]
@phillysnow We did at the every beginning. It was kind of hard to figure out how to help here. I decided not to think about anything related to getStaticProps because we want to allow users to have the flexibility they might need within that function, and by making a helper we'd likely be taking away that flexibility. 

I would definitely love to revisit the topic, though, support previews felt like the lowest hanging fruit. Much more obvious how we can help there vs other methods. Do you have any kind of proposal in mind or would you be interested in a sort of brainstorm session?


@Heyrows Oh I think I just got that from the NextJS documentation. I am experiencing some weird bugs right now so perhaps that would be a better way, I'll report back!

@pvpg We talked about this, just don't have a solid answer for you quite yet. I'll reach out to you on slack this week, though, to learn more.

**Comment by phillysnow** [comment]
@dayhaysoos I'd be really up for brainstorming on this, at least in terms of presenting the challenges and workarounds that currently exist for this. It would probably be beneficial to include @lihbr in that conversation as she worked on the nuxt plugin which gets all the routes to generate automatically for the user:
https://github.com/nuxt-community/prismic-module/blob/master/src/generator.js

**Comment by lihbr** [comment]
> @dayhaysoos I'd be really up for brainstorming on this, at least in terms of presenting the challenges and workarounds that currently exist for this. It would probably be beneficial to include @lihbr in that conversation as she worked on the nuxt plugin which gets all the routes to generate automatically for the user:
> https://github.com/nuxt-community/prismic-module/blob/master/src/generator.js

Just a side note as this generator is deprecated and built-in into Nuxt now :)

**Comment by chamois-d-or** [comment]
@dayhaysoos , preview works great, but I tried using the shareable link to share a draft version and it does not work (I tested on my computer and another computer too)
