### ISSUE TITLE
Hydration error using `<PrismicLink/>`

### ISSUE THREAD

**Issue by DennisKraaijeveld** [prismicio/prismic-next#40]
### Versions

     
    "@prismicio/client": "^6.7.1",
    "@prismicio/helpers": "^2.3.3",
    "@prismicio/next": "^0.1.5",
    "@prismicio/react": "^2.5.0",
    "@prismicio/slice-simulator-react": "^0.2.2",
    "next": "12.3.0",
    "react": "18.2.0",

### Reproduction

When using PrismicLink to render internal links it will create an `a` element inside an `a` element.

`{menu.data?.links.map((menuLink, index) => (
                    <li key={menuLink.label}>
                      <PrismicLink field={menuLink.link}>
                        <span className="text-base font-medium text-gray-500 hover:text-gray-900">
                          test
                        </span>
                      </PrismicLink>
                    </li>
                  ))}`

### What is expected?

This gives a hydration error in React 18 since an `a` element cant be a child of another `a` element. I did follow the docs and guides and I have no clue why this bug did occur in my app.

**Comment by DennisKraaijeveld** [comment]
@angeloashmore Never mind! Found the issue and that is that I followed the docs and set an internal link component through the PrismicProvider like this:

`
    internalLinkComponent={({ href, ...props }) => (
        <Link href={href}>
          <a {...props} />
        </Link>
      )}
`

This is still the way to go according to the example repo's and the documentation, but this will cause Hydration errors.

**Comment by angeloashmore** [comment]
Hi @DennisKraaijeveld, thanks for the report!

The documentation *should* be correct unless you have the `experimental.newNextLinkBehavior` Next.js option enabled in `next.config.js. Details on that option are available in vercel/next.js#36436.

Do you have `newNextLinkBehavior` enabled in your app?

If so, you can set `internalLinkComponent` like the following example if you haven't already. Note that `Link` can be passed directly to `internalLinkComponent`.

```
// pages/_app.js

import Link from "next/link";
import { PrismicLink, PrismicProvider } from "@prismicio/react";
import { PrismicPreview } from "@prismicio/next";

export default function App({ Component, pageProps }) {
  return (
    <PrismicProvider internalLinkComponent={Link}>
      <PrismicPreview repositoryName="your-repo-name">
        <Component {...pageProps} />
      </PrismicPreview>
    </PrismicProvider>
  );
}
```

When Next 13 is released with `newNextLinkBehavior` enabled by default, we will update the documentation with a note on how to configure it for Next 12.
