### ISSUE TITLE
Next 13 PrismicPreview

### ISSUE THREAD

**Issue by mikefrancis** [prismicio/prismic-next#50]
### Versions

- `@prismicio/next`: 1.0.0
- `next`: 13.0.3
- node: 16.16.0

### Reproduction

Follow set up instructions with a Next 13 app:

https://prismic.io/docs/setup-nextjs

### What is expected?

No type error

### What is actually happening?

See the following type error:

![Screenshot 2022-11-17 at 09 50 27](https://user-images.githubusercontent.com/1672610/202417284-e62ab9d0-5e32-4e95-9743-a84d7f21f8ac.png)

**Comment by angeloashmore** [comment]
Hi @mikefrancis, thanks for the report. This should be fixed as of `v1.0.1`.

You can update to the latest version with the following command:

```sh
npm install @prismicio/next@latest
```

If this doesn't fix the issue, please let me know and I'll take another look. Thanks!
