### ISSUE TITLE
Module not found: Can't resolve 'next/navigation'

### ISSUE THREAD

**Issue by waleed-alfaifi** [prismicio/prismic-next#67]
I am just starting out installing dependencies as in the [starter docs](https://prismic.io/docs/setup-nextjs) and as soon as I add the `<PrismicPreview>...</PrismicPreview>` part, I get the following error:

```bash
../../node_modules/@prismicio/next/dist/PrismicPreviewClient.js:5:0
Module not found: Can't resolve 'next/navigation'

Import trace for requested module:
../../node_modules/@prismicio/next/dist/PrismicPreview.js
../../node_modules/@prismicio/next/dist/index.js
./src/pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
```

After some digging in the `@prismicio/next` module, I found that the [src/PrismicPreviewClient.tsx](https://github.com/prismicio/prismic-next/blob/main/src/PrismicPreviewClient.tsx#L5) is using `next/navigation` which does not seem to be exported by next nor is it documented in their website. Removing that liner actually solves the problem.

Is this to support the new `app` router? Well in that case this breaks the existing `pages` router! 

### Versions

- `@prismicio/next`:  v1.1.0
- `next`: v12.3.1
- node: v16.19.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

In the `pages/_app.tsx` file I added the following:

```tsx
import { PrismicProvider } from '@prismicio/react'
import { PrismicPreview } from '@prismicio/next'
import { repositoryName } from '../../prismicio'

<PrismicProvider>
   <PrismicPreview repositoryName={repositoryName}>
           ...
   </PrismicPreview>
</PrismicProvider>
```

### Steps to reproduce
Please follow the steps at the [setup Prismic docs](https://prismic.io/docs/setup-nextjs#add-prismicpreview)

### What is expected?
Expected the app to work normally with preview supported

### What is actually happening?
The app breaks and shows the above error message.

**Comment by waleed-alfaifi** [comment]
Moreover I also get the same error for the following modules:

- `next/headers` which is used in [src/enableAutoPreviews.ts](https://github.com/prismicio/prismic-next/blob/main/src/enableAutoPreviews.ts#L2)
- `next/navigation` which is again used in [src/redirectToPreviewURL.ts](https://github.com/prismicio/prismic-next/blob/406370667d1527d90893d8b795f50e609f5d5096/src/redirectToPreviewURL.ts#L1)

Replacing them with the following imports worked, respectively:
- `import { getCookieParser as cookies } from 'next/dist/server/api-utils'`
- `import { redirect } from 'next/dist/server/api-utils'`

But I don't think these packages should be used as they are not documented and will probably change without any further notice.

**Comment by angeloashmore** [comment]
Hi @waleed-alfaifi, thanks for the detailed report!

`@prismicio/next` v1.0 and later requires at least Next.js 13.0, which should include the modules you listed (including `next/navigation`).

Upgrading from Next.js 12 to 13 should be a straightforward upgrade. See the upgrade guide here: https://nextjs.org/docs/pages/building-your-application/upgrading/version-13

If you are still experiencing issues with `@prismicio/next` after upgrading to Next.js 13, please comment here again and I will investigate.

Thank you! 🙂

**Comment by waleed-alfaifi** [comment]
@angeloashmore OK that might solve the problem but you should really mention it in the docs that you don't support Next 12 anymore. That way one won't have to go through the trouble of debugging a problem that should have not existed.

**Comment by angeloashmore** [comment]
@waleed-alfaifi It is mentioned in `@prismicio/next`'s documentation: https://prismic.io/docs/technical-reference/prismicio-next

However, it isn't listed in the main Prismic + Next.js guides. I'll make sure we add that note. Thanks for the feedback!
