### ISSUE TITLE
Updating library into latest version causes app to crash because of the "PrismicPreview" component.

### ISSUE THREAD

**Issue by aarnipavlidi** [prismicio/prismic-next#69]
### Versions

- `@prismicio/next`: 1.1.0
- `next`: 13.4.3
- node: v17.8.0

### Reproduction

Was updating my current project libraries and had only problem when updating this library into latest version. Current package.json  looks following (on my latest branch, not at master yet):

`  "dependencies": {
    "@apollo/client": "^3.7.14",
    "@prismicio/client": "^6.8.0",
    "@prismicio/helpers": "^2.3.9",
    "@prismicio/next": "^1.1.0",
    "@prismicio/react": "^2.6.1",
    "@prismicio/slice-simulator-react": "^0.2.3",
    "@types/node": "18.11.12",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.9",
    "apollo-link": "^1.2.14",
    "apollo-link-http": "^1.5.17",
    "classnames": "^2.3.2",
    "eslint": "8.29.0",
    "eslint-config-next": "13.0.6",
    "graphql": "^15.8.0",
    "html-react-parser": "^3.0.16",
    "next": "^13.4.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.4"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^3.3.1",
    "@graphql-codegen/client-preset": "^3.0.1",
    "@graphql-codegen/fragment-matcher": "^4.0.1",
    "@prismicio/types": "^0.2.7",
    "@slicemachine/adapter-next": "^0.1.3",
    "@types/node-fetch": "^2.6.4",
    "autoprefixer": "^10.4.13",
    "dotenv": "^16.0.3",
    "node-fetch": "^2.6.11",
    "postcss": "^8.4.19",
    "slice-machine-ui": "^1.0.3",
    "tailwindcss": "^3.3.2",
    "ts-node": "^10.9.1"
  }`

I have found the issue at on my `_app.tsx` file, which looks following:

![Screenshot 2023-05-19 at 16 23 50](https://github.com/prismicio/prismic-next/assets/55801258/a4df34cf-f3f6-4871-a3b8-3c51d260137c)

And the variable called _prismicRepositoryName_ is equal to the following:

`export const prismicRepositoryName = process.env.PRISMIC_REPOSITORY_NAME || '';`

So if I either remove the **PrismicPreview** component or "hardcode" the variable into string e.g:

`<PrismicPreview repositoryName={"myRepositoryName"}>`

Then following error won't come:

<img width="528" alt="Screenshot 2023-05-19 at 16 27 41" src="https://github.com/prismicio/prismic-next/assets/55801258/f211d480-59c4-4c89-8cdf-d13362e17a01">

### Steps to reproduce

1) Make sure that **PrismicPreview** components "repositoryName" prop is using the env. variable
2) Install first **@prismicio/next** version 1.0.3
3) Then install latest version (1.1.0)
4) App should crash and error regarding invalid repository name

### What is expected?

Expecting that I could use env. variables with the **PrismicPreview** component, so that app won't crash on initial load.

### What is actually happening?

App crashing on initial load.

**Comment by aarnipavlidi** [comment]
Here is the copy of current project on latest branch:

`{
  "name": "portfolio",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "lint:fix": "npm run lint -- --fix",
    "prismic-types": "ts-node-script --skip-project scripts/codegen.ts",
    "slicemachine": "start-slicemachine"
  },
  "dependencies": {
    "@apollo/client": "^3.7.14",
    "@prismicio/client": "^6.8.0",
    "@prismicio/helpers": "^2.3.9",
    "@prismicio/next": "^1.0.3",
    "@prismicio/react": "^2.6.1",
    "@prismicio/slice-simulator-react": "^0.2.3",
    "@types/node": "18.11.12",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.9",
    "apollo-link": "^1.2.14",
    "apollo-link-http": "^1.5.17",
    "classnames": "^2.3.2",
    "eslint": "8.29.0",
    "eslint-config-next": "13.0.6",
    "graphql": "^15.8.0",
    "html-react-parser": "^3.0.16",
    "next": "^13.4.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.4"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^3.3.1",
    "@graphql-codegen/client-preset": "^3.0.1",
    "@graphql-codegen/fragment-matcher": "^4.0.1",
    "@prismicio/types": "^0.2.7",
    "@slicemachine/adapter-next": "^0.1.3",
    "@types/node-fetch": "^2.6.4",
    "autoprefixer": "^10.4.13",
    "dotenv": "^16.0.3",
    "node-fetch": "^2.6.11",
    "postcss": "^8.4.19",
    "slice-machine-ui": "^1.0.3",
    "tailwindcss": "^3.3.2",
    "ts-node": "^10.9.1"
  }
}
`

And working on following project/branch:

https://github.com/aarnipavlidi/portfolio/tree/feature/6-create-hero-sectioncomponent-for-prismic

If you want to clone and reproduce problem I am having.

**Comment by angeloashmore** [comment]
Hi @aarnipavlidi, apologies for the late reply. `repositoryName` should always have a value; it should be never `undefined` or `""`.

In the case that you don't have a repository name, `<PrismicPreview>` should not be added to the tree.

Is there a reason `process.env.PRISMIC_REPOSITORY_NAME` isn't always set? Are you able to provide a static fallback?

**Comment by angeloashmore** [comment]
I'm going to close this issue since this is be design, but we can continue the discussion and re-open if we determine we should change how `<PrismicPreview>` reacts to falsy `repositoryName` values. Thank you!
