### ISSUE TITLE
PrismicNextImage broken with Next 13.4.8

### ISSUE THREAD

**Issue by AugusDogus** [prismicio/prismic-next#77]
### Versions

- `@prismicio/next`:  1.3.2
- `next`:  13.4.8
- node:  18.13.0

### Reproduction

Attempt to use PrismicNextImage with Next 13.4.8

### What is actually happening?

`next dev` & `next build` both fail with the error:

`Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at PrismicNextImage (/Users/augie/dev/redacted/node_modules/.pnpm/@prismicio+next@1.3.2_@prismicio+client@7.1.0_next@13.4.8_react@18.2.0/node_modules/@prismicio/next/dist/PrismicNextImage.cjs:23:29)`

**Comment by angeloashmore** [comment]
Fixed as of `v1.3.3` in https://github.com/prismicio/prismic-next/pull/79.
