### ISSUE TITLE
Don't require the full `context` object to use `enableAutoPreviews()`

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-next#8]
In the example `createClient()` function, we ask users to pass the whole context object so we can pass it to `enableAutoPreviews()`.

```ts
// In a page file

export const getStaticProps = (context) => {
  const client = createClient({ context })
}
```

```ts
// prismicio.js

export const createClient = ({ req, context } = {}) => {
  const client = prismic.createClient(endpoint)

  enableAutoPreviews({ client, req, context })

  return client
}
```

This causes an ergonomic issue when you need something from within `context` in `getStaticProps` or its sibling APIs.

For example, using `params` from `context` requires using `context.params`. This is non-idiomatic.

```ts
export const getStaticProps = async (context) => {
  const client = createClient({ context })

  const documents = await client.getByUID('page', context.params.uid)
}
```

It is more idiomatic to destructure `params` from `context`.

```ts
export const getStaticProps = async ({ params }) => {
  const client = createClient({ context })

  const documents = await client.getByUID('page', params.uid)
}
```

However, this means we can no longer pass the full `context` object to `createClient` (which is only passed directly to `enableAutoPreviews()`).

## Proposal

Change `enableAutoPreviews()` to only require the data it needs. Rather than requiring the full `context` object, it can accept just the `previewData` property from within `context`.

This changes a page's `getStaticProps()` to this:

```ts
export const getStaticProps = async ({ params, previewData }) => {
  const client = createClient({ previewData })

  const documents = await client.getByUID('page', params.uid)
}
```

This improves on the current strategy in to ways:

1. It allows for using `params` easily.
2. It conveys intent; passing `previewData` to `createClient` shows that the client is "preview-capable."

The `createClient()` function would need to be updated appropriately:

```ts
// prismicio.js

export const createClient = ({ req, previewData } = {}) => {
  const client = prismic.createClient(endpoint)

  enableAutoPreviews({ client, req, previewData })

  return client
}
```

**Comment by dayhaysoos** [comment]
Fixed with #12
